fix(conflicts): toolchain components
Removing this line fixed issues I got with errors such as:
```
error: failed to install component: 'clippy-preview-aarch64-apple-darwin', detected conflict: 'bin/cargo-clippy'
```