client refactor + iOS client (#95)
* fix(conflicts): toolchain components

Removing this line fixed issues I got with errors such as:
```
error: failed to install component: 'clippy-preview-aarch64-apple-darwin', detected conflict: 'bin/cargo-clippy'
```

* feat: wasm builds -- no lint

* chore: further lint

* checkpoiunt: standard rust client working with websocket

* checkpoint: both build -- no lint

* nits